// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {wavelog} from '../models';

export function BrowseLogFile():Promise<string>;

export function GetConfig():Promise<main.ConfigDTO>;

export function GetStationProfiles():Promise<Array<wavelog.StationProfile>>;

export function SaveConfig(arg1:main.ConfigDTO):Promise<void>;

export function SyncAll():Promise<void>;

export function SyncFromWavelog():Promise<void>;
