// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLogFile() {
  return window['go']['main']['App']['BrowseLogFile']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStationProfiles() {
  return window['go']['main']['App']['GetStationProfiles']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncAll() {
  return window['go']['main']['App']['SyncAll']();
}

export function SyncFromWavelog() {
  return window['go']['main']['App']['SyncFromWavelog']();
}
